package main

import "fmt"

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

func main() {
	const max = 4e6 //Do not exceed 4000000
	var sum, p, n int32 = 0, 0, 1
	for sum < max {
		val := p + n
		if val&1 == 0 {
			sum += val
		}
		p = n
		n = val
	}
	fmt.Printf("Sum = %d\n", sum) //outputs: 4613732
}
